### ISSUE TITLE
Breaking changes to BoxGeometry in three 0.125+

### ISSUE THREAD

**Issue by elichad** [stur86/crystvis-js#16]
Release [Three 0.125](https://github.com/mrdoob/three.js/releases/tag/r125) changed the BoxGeometry class so it no longer has a `vertices` attribute - this affects the `BoxMesh` class [here](https://github.com/stur86/crystvis-js/blob/master/lib/primitives/cell.js#L42). There might be other breaking changes too.

The line linked above is breaking when I try to load a file into the renderer through Galaxy (reverting to three 0.124 fixes it). This doesn't seem to break the demo or tests, though, which is odd as they also call `BoxMesh`.

**Comment by stur86** [comment]
Thanks, I'll take a look at this!

**Comment by elichad** [comment]
The tests do actually fail with 0.125, I had some caching happening without realising. Demo still seems to work though.

**Comment by stur86** [comment]
Fixed in https://github.com/stur86/crystvis-js/commit/74556f9c288645d9a2d620c784f2a686217c944c.
